name: CI

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    env:
      BUNDLE_GEMFILE: gemfiles/rails_${{ matrix.rails_version }}.gemfile
    strategy:
      fail-fast: false
      matrix:
        ruby: ["2.6", "2.7", "3.0", "3.1", ruby-head]
        rails_version: ["6.0", "7.0"]
        include:
          - ruby: "2.6"
            rails_version: "5.0"
          - ruby: "2.6"
            rails_version: "5.1"
          - ruby: "2.7"
            rails_version: "5.0"
          - ruby: "2.7"
            rails_version: "5.1"
        exclude:
          - ruby: "2.6"
            rails_version: "7.0"
          - ruby: "3.1"
            rails_version: "6.0"
          - ruby: ruby-head
            rails_version: "6.0"

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true # 'bundle install' and cache gems
        ruby-version: ${{ matrix.ruby }}
    - name: Run tests
      run: bundle exec rake
